sonar.projectKey=scriptsl0th_my-portfolio
sonar.organization=scriptsl0th

sonar.projectName=Portfolio
sonar.projectVersion=0.0.0
sonar.sourceEncoding=UTF-8

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.exclusions=**/node_modules/**,**/dist/**,**/server/**,**/*.spec.ts

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=**/*.spec.ts,**/environments/**
